if(0<M("[data-list]").selector.length){var currentApp=M("[data-list]").data("list"),alist=appList,savedName=M.storage("io.github.romeoh.user.name"),nameStr0=savedName,nameStr1=uniValue(savedName)?savedName+"\uc740":savedName+"\ub294",nameStr2=uniValue(savedName)?savedName+"\uacfc":savedName+"\uc640";savedName&&(alist=appList.replace(/@\ub098\ub294@/g,"@"+nameStr1+"@").replace(/@\ub098\uc5d0\uac8c@/g,"@"+nameStr0+"\uc5d0\uac8c@").replace(/@\ub2f9\uc2e0\uc758@/g,"@"+nameStr0+"\uc758@").replace(/@\ub098\uc758@/g,
"@"+nameStr0+"\uc758@").replace(/@\ub098\uc640@/g,"@"+nameStr2+"@").replace(/@\ub0b4@/g,"@"+nameStr0+"@").replace(/@\ub9d0\uad04\ub7c9\uc774@/g,"@"+nameStr0+"@"));var d=new Date,month=d.getMonth()+1,date=d.getDate();15<date&&(month=12==month?1:month+1);alist=alist.replace(/@/g,"").replace(/\uc774\ub2ec\uc758/,month+"\uc6d4\uc758");M("[data-list]").html(alist);M('[data-app="'+currentApp+'"]').prepend("span",{className:"ico sel"});M("#eventContainer").before("div",{className:"listbox"}).before("a",
{id:"viewCategory"});var category=M.storage("io.github.romeoh.user.category")||"all",str="",categoryText;M.storage("io.github.romeoh.user.category",category);"all"===category?M("[data-page]").css("display","block"):(M("[data-page]").css("display","none"),M("[data-"+category+"]").css("display","block"));M("[data-new]").css("display","block");str+="<ul>";str+='<li data-category="all">\ubaa8\ub450</li>';str+='<li data-category="hot">\uc778\uae30</li>';str+='<li data-category="recommand">\ucd94\ucc9c</li>';
str+='<li data-category="me">\uc790\uae30\uc560</li>';str+='<li data-category="love">\uc5f0\uc560</li>';str+='<li data-category="game">\uac8c\uc784</li>';str+='<li data-category="fun">\uc7ac\ubbf8</li>';str+='<li data-category="heart">\uc2ec\ub9ac\ud14c\uc2a4\ud2b8</li>';str+="</ul>";M(".listbox").html(str);categoryText=M('[data-category="'+category+'"]').addClass("sel").text();M("#viewCategory").addClass("btn_rlist").data("isopen","false").text(categoryText).on("click",listBoxListener);M("[data-category]").on("click",
function(a,e){M("[data-category]").removeClass("sel");category=e.addClass("sel").data("category");M("#viewCategory").removeClass("sel").data("isopen","false").text(e.text());M(".listbox").css("display","none");M.storage("io.github.romeoh.user.category",category);M("[data-page]").css("display","none");"all"===category?M("[data-page]").css("display","block"):M("[data-"+category+"]").css("display","block");M("[data-new]").css("display","block")});if(0<M("#snsBox").selector.length){var appNo=M("[data-list]").data("list"),
appName=M('[data-app="'+appNo+'"]').data("page");M("#snsBox").append("div",{className:"fb-like"});M(".fb-like").data("href","http://romeoh.github.io/kakaoStory/html/"+appName+".html").data("width","450").data("layout","button_count").data("showFaces","true").data("send","true")}(function(a,e,f){var h=a.getElementsByTagName(e)[0];a.getElementById(f)||(a=a.createElement(e),a.id=f,a.src="//connect.facebook.net/ko_KR/all.js#xfbml=1&appId=519730578083610",h.parentNode.insertBefore(a,h))})(document,"script",
"facebook-jssdk")}var eventList=M.storage("event_list")||"EVENT";M.storage("event_list",eventList);"EVENT"===eventList?(M("#btnEvent").addClass("on"),M("#eventContainer").css("display","block"),M("#replyContainer").css("display","none")):"REPLY"===eventList&&(M("#btnReply").addClass("on"),M("#eventContainer").css("display","none"),M("#replyContainer").css("display","block"),M("#viewCategory").css("display","none"));
M("#btnEvent").on("click",function(){eventList="EVENT";M.storage("event_list",eventList);M("#btnEvent").addClass("on");M("#btnReply").removeClass("on");M("#eventContainer").css("display","block");M("#replyContainer").css("display","none");M("#viewCategory").css("display","block")});
M("#btnReply").on("click",function(){eventList="REPLY";M.storage("event_list",eventList);M("#btnReply").addClass("on");M("#btnEvent").removeClass("on");M("#eventContainer").css("display","none");M("#replyContainer").css("display","block");M("#viewCategory").css("display","none");M("#viewCategory").removeClass("sel");M(".listbox").css("display","none")});
function listBoxListener(a,e){"false"===M("#viewCategory").data("isopen")?(M("#viewCategory").data("isopen","true").addClass("sel"),M(".listbox").css("display","block")):(M("#viewCategory").data("isopen","false").removeClass("sel"),M(".listbox").css("display","none"))}M("#btnMacao").on("click",function(){window.location.href="http://goo.gl/HMF8gs"});M("#btnMain").on("click",function(){randomUrl()});
function randomUrl(){idx=getRandom(1,totalApp);url=M('[data-app="'+idx+'"]').first().attr("href");window.location.href=url}function getRandom(a,e){return Math.floor(Math.random()*(e-a)+a)}eventTxt=['<a href="http://goo.gl/A2UOmW">\uae68\uc720 \ud398\uc774\uc2a4\ubd81 \ud398\uc774\uc9c0 \uc624\ud508\ud588\ub2e8\uae68\uc720~</a>'];M("nav").css("display","block");M("#userName").on("change",function(a,e){M.storage("io.github.romeoh.user.name",e.val())}).val(M.storage("io.github.romeoh.user.name")||"");
M("#boyBox a").on("click",function(){M("#boyBox a").addClass("checked");M("#girlBox a").removeClass("checked")});M("#girlBox a").on("click",function(){M("#boyBox a").removeClass("checked");M("#girlBox a").addClass("checked")});M("#btnStory").on("click",function(){validation({media:"story"})});M("#btnTwitter").on("click",function(){validation({media:"twitter"})});M("#btnFacebook").on("click",function(){validation({media:"facebook"})});M("#btnMe2day").on("click",function(){validation({media:"me2day"})});
M("#btnKakao").on("click",function(){action({media:"talk"})});
function validation(a){a=a||{};M.storage("io.github.romeoh.user.platform",a.media);if(0<M("#boyBox a").selector.length){if(!M("#boyBox a").hasClass("checked")&&!M("#girlBox a").hasClass("checked"))return alert("\uc131\ubcc4\uc744 \uc120\ud0dd\ud574 \uc8fc\uc138\uc694."),!1;M("#boyBox a").hasClass("checked")?a.sexType="boy":M("#girlBox a").hasClass("checked")&&(a.sexType="girl");M.storage("io.github.romeoh.user.sexType",a.sexType)}if(0<M("#userName").selector.length){if(""===M("#userName").val())return alert("\uc774\ub984\uc744 \uc785\ub825\ud574 \uc8fc\uc138\uc694."),
!1;a.userName=M("#userName").val()}if(0<M("#selColor").selector.length){if("-1"===M("#selColor").val())return alert("\uc88b\uc544\ud558\ub294 \uc0c9\uc0c1\uc744 \uc120\ud0dd\ud574 \uc8fc\uc138\uc694."),!1;a.color=M("#selColor").val()}if(0<M("#selAlpha").selector.length){if("-1"===M("#selAlpha").val())return alert("\ub5a0\uc624\ub974\ub294 \uc54c\ud30c\ubcb3\uc744 \uc120\ud0dd\ud574 \uc8fc\uc138\uc694."),!1;a.alphabet=M("#selAlpha").val()}if(0<M("#selCoffee").selector.length){if("-1"===M("#selCoffee").val())return alert("\ucee4\ud53c\ub97c \uc8fc\ubb38\ud574 \uc8fc\uc138\uc694."),
!1;a.coffee=M("#selCoffee").val()}if(0<M("#userAge").selector.length){if(""===M("#userAge").val())return alert("\uc0dd\ub144\uc744 \uc785\ub825\ud574 \uc8fc\uc138\uc694."),!1;a.bornYear=M("#userAge").val();M.storage("io.github.romeoh.user.bornYear",M("#userAge").val())}if(0<M("#selYear").selector.length){if("-1"===M("#selYear").val())return alert("\uc0dd\ub144\uc744 \uc120\ud0dd\ud574 \uc8fc\uc138\uc694."),!1;a.bornYear=M("#selYear").val();M.storage("io.github.romeoh.user.bornYear",M("#selYear").val())}if(0<
M("#selMonth").selector.length){if("-1"===M("#selMonth").val())return alert("\ud0dc\uc5b4\ub09c \ub2ec\uc744 \uc120\ud0dd\ud574\uc8fc\uc138\uc694."),!1;a.bornMonth=M("#selMonth").val();M.storage("io.github.romeoh.user.bornMonth",M("#selMonth").val())}if(0<M("#selDate").selector.length){if("-1"===M("#selDate").val())return alert("\ud0dc\uc5b4\ub09c \ub0a0\uc744 \uc120\ud0dd\ud574\uc8fc\uc138\uc694."),!1;a.bornDate=M("#selDate").val();M.storage("io.github.romeoh.user.bornDate",M("#selDate").val())}if(0<
M("#selBlood").selector.length){if("-1"===M("#selBlood").val())return alert("\ud608\uc561\ud615\uc744 \uc120\ud0dd\ud574\uc8fc\uc138\uc694."),!1;a.blood=M("#selBlood").val()}if(0<M("#selSex").selector.length){if("-1"===M("#selSex").val())return alert("\uc131\ubcc4\uc744 \uc120\ud0dd\ud574\uc8fc\uc138\uc694."),!1;a.sexType=M("#selSex").val()}if(0<M("#selActor").selector.length){if("-1"===M("#selActor").val())return alert("\uc0c1\ub300\uc5f0\uae30\uc790\ub97c \uc120\ud0dd\ud574\uc8fc\uc138\uc694."),
!1;a.actor=M("#selActor").val()}if(0<M("#selTall").selector.length){if("-1"===M("#selTall").val())return alert("\ub098\uc758 \ud0a4\ub97c \uc120\ud0dd\ud574\uc8fc\uc138\uc694."),!1;a.tall=M("#selTall").val()}if(0<M("#selIndian").selector.length){if("-1"===M("#selIndian").val())return alert("\uc778\ub514\uc548 \ubd80\uc871\uc744 \uace0\ub974\uc138\uc694."),!1;a.indian=M("#selIndian").val()}action(a)}
function uniValue(a){if(a){a=a.substr(a.length-1).charCodeAt(0)-44032;var e=a%28;parseInt((a-e)/28%21,10);return 0===e?!1:!0}}var bannerData;function showad(){}function closeBanner(){M("#goStore").animate({opacity:"0",time:".3s"},function(a,e){e.css("display","none")});console.log("closeBanner()")}function goStore(){window.location.href=bannerData.link;console.log("goStore()")}
dataBanner=[{url:"bnnr_hippop.html",link:"http://goo.gl/BNYgT"},{url:"bnnr_buam.html",link:"http://goo.gl/WrRJr"},{url:"bnnr_dance.html",link:"http://goo.gl/otEy6"},{url:"bnnr_alice.html",link:"http://goo.gl/qldVb"}];
function sendData(a){var e=a||{},f=e.media||"story",h=e.id||"gaeyou",c=e.ver||"1.0",g=e.app||"\uae68\uc54c\uc720\uba38:",l=e.title||"",m=e.url||"";if("talk"==f)return l=e.msg||l||"",kakao.link("talk").send({msg:l,url:m,appid:h,appver:c,appname:g,type:"link"}),test="\u2665\u2665 [\uce74\ud1a1\uce5c\uad6c \ucd08\ub300] \u2665\u2665\n",test+="appId: "+h+"\n",test+="appVersion: "+c+"\n",test+="appName: "+g+"\n",test+="msg: \n",test+="-----------\n",test+=l+"\n",test+="-----------\n",test+="url: "+m+"\n",
test+="--------------------------------------------\n",console.log(test),!1;if("story"==f){var f=e.post||"",k=e.desc||"",e=e.img||"",n={title:l,desc:k,imageurl:[e],type:"article"},f=f+"\n\n"+m;kakao.link("story").send({appid:h,appver:c,appname:g,post:f,urlinfo:M.json(n)});test="\u2665\u2665 [\uce74\uc2a4\ub85c \uacf5\uc720] \u2665\u2665\n";test+="appId: "+h+"\n";test+="appVersion: "+c+"\n";test+="appName: "+g+"\n";test+="post: \n";test+="-----------\n";test+=f+"\n";test+="-----------\n";test+="title: "+
l+"\n";test+="desc: "+k+"\n";test+="img: "+e+"\n";test+="--------------------------------------------\n";console.log(test);return!1}if("twitter"==f)return k="",f=e.twit||e.post||"",h=m.length+5,c=f.length+h+1,e=140,twit=c>=e?f.substr(0,e-h)+"...\n"+m:f+"\n"+m,twit=twit.replace(/\n\n/g,"\n"),k=k+"https://twitter.com/intent/tweet?text="+encodeURIComponent(twit),top.location.href=k,test="\u2665\u2665 [\ud2b8\uc704\ud130\ub85c \uacf5\uc720] \u2665\u2665\n",test+="twit: \n",test+="-----------\n",test+=
twit+"\n",test+="-----------\n",console.log(test),!1;if("me2day"==f)return k="",f=e.twit||e.post||"",g=e.tag||"\ubbf8\ud22c\ub370\uc774\ub97c \ub354 \uc7ac\ubbf8\uc788\uac8c \uae68\uc54c\uc720\uba38 SNS \ud14c\uc2a4\ud2b8 \uc2ec\ub9ac\ud14c\uc2a4\ud2b8",h=m.length+5,c=f.length+h+1,e=150,me2=c>=e?f.substr(0,e-h)+"...\n"+m:f+"\n"+m,me2=me2.replace(/\n\n/g,"\n"),k+="http://me2day.net/posts/new",k+="?new_post[body]=",k+=encodeURIComponent(me2),k+="&new_post[tags]=",k+=encodeURIComponent(g),top.location.href=
k,test="\u2665\u2665 [\ubbf8\ud22c\ub370\uc774\ub85c \uacf5\uc720] \u2665\u2665\n",test+="post: \n",test+="-----------\n",test+=me2+"\n",test+="-----------\n",console.log(test),!1;if("facebookSharer"==f)return f=e.post||"",e=e.img||"",k="http://www.facebook.com/sharer.php",k+="?s=100",k+="&p[title]="+encodeURIComponent(f.replace(/\[.+\]/g,"")),k+="&p[summary]="+encodeURIComponent(l),k+="&p[url]="+encodeURIComponent(m),k+="&p[images][0]="+encodeURIComponent(e),top.location.href=k,!1;if("facebook"==
f)return M("body").prepend("script",{src:"https://connect.facebook.net/en_US/all.js",type:"text/javascript",id:"facebookScript"}),M("#facebookScript").on("load",function(c,e){var f=a||{},k=f.mode||"real",g=f.feed||"feed",h=f.method||"post",l=f.photo||f.img||"",n=f.post||"",f=f.scope||"publish_actions, user_photos",p={},n=n+"\n\n"+m;"feed"==g?p={message:n,picture:l}:"photo"==g&&(p={message:n,url:l});FB.init({appId:"real"==k?"575459299155222":"199304076906232",channelUrl:"//WWW.YOUR_DOMAIN.COM/channel.html",
status:!0,cookie:!0,xfbml:!0});FB.login(function(a){a.authResponse&&FB.api(/me/+g,h,p,function(a){console.log(a);!a||a.error?alert("\uc8c4\uc1a1\ud569\ub2c8\ub2e4.\n\uc624\ub958\uac00 \ubc1c\uc0dd\ud588\uc2b5\ub2c8\ub2e4."):alert("\ud398\uc774\uc2a4\ubd81\uc5d0 \ub4f1\ub85d \ub418\uc5c8\uc2b5\ub2c8\ub2e4.")})},{scope:f});test="\u2665\u2665 [\ud398\uc774\uc2a4\ubd81\uc73c\ub85c \uacf5\uc720] \u2665\u2665\n";test+="feed: "+g+"\n";test+="method: "+h+"\n";test+="photo: "+l+"\n";test+="message: \n";test+=
"-----------\n";test+=n+"\n";test+="-----------\n";console.log(test)}),!1;if("band"==f)return n="",f=e.post||"",h=m.length+3,c=f.length+h+1,e=300,bandPost+="["+g+"]\n",bandPost+=l+": "+f,b=c>=e?bandPost.substr(0,e-h)+"..."+m:bandPost+" "+m,n=n+"bandapp://create/post?text="+encodeURIComponent(bandPost),n+="#Intent;package=com.nhn.android.band;end;",top.location=k,!1}
function process(a,e){return"object"===getDataType(a)||"array"===getDataType(a)?Math.floor(Math.random()*a.length):Math.floor(Math.random()*(e-a)+a)}function shuffle(a,e){var f=a.length;e=e||f;for(var h,c;0<f;)c=Math.floor(Math.random()*f),f--,h=a[f],a[f]=a[c],a[c]=h;a.length=e;return a}
function getDataType(a){if("string"===typeof a)return"string";if("number"===typeof a)return"number";if(a.constructor===Object)return"object";if(a.constructor===Array)return"array";if(a.constructor===Function)return"function";if(a.constructor===Boolean)return"boolean"}window.addEventListener("hashchange",function(){window.location.reload()});window.addEventListener("load",initPoll,!1);
function initPoll(){function a(){var a=M("[data-poll]").data("poll");if(l[a])return alert("\uc774\ubbf8 \ud22c\ud45c\ud55c \ub7ad\ud0b9\uc785\ub2c8\ub2e4."),!1;l[a]="true";console.log(l);M.storage("io.github.romeoh.poll",M.json(l))}function e(a){M("[data-poll]").data("poll");M(".tinfo").css("display","block").html('<div><span class="ico i"></span> \ubc18\uc601\ub418\uc5c8\uc2b5\ub2c8\ub2e4. <br>\uac10\uc0ac\ud569\ub2c8\ub2e4. \uc544\ub798 SNS\ub85c \uacb0\uacfc\ub97c \ud655\uc778\ud558\uc138\uc694.</div>');
console.log(a)}if(0<M("[data-poll]").selector.length){var f=window.location.hash.replace("#",""),h,c="";if(""===f)return window.location.hash=rankList[0].idx,window.location.reload(),!1;for(var g=0;g<rankList.length;g++)rankList[g].idx==f&&(h=rankList[g]);if(void 0==h)return window.location.hash=rankList[0].idx,window.location.reload(),!1;M("#rankTitle h2").html(h.title.replace(/ VS /g,' <span class="vs">VS</span> '));M("#question").html('<span class="ico_q">Q</span>'+h.q);if("A"===h.type)for(M("#pollType").addClass("poll_content"),
g=0;g<h.list.length;g++)0!=g&&(c+='<div class="ico_ent ico_vs">VS</div>'),c+='<div class="plist">',c+='\t<span><img src="'+h.list[g].photo+'" width="80px"></span>',c+="\t<p>"+h.list[g].title+"</p>",c+='\t<div class="btn_poll pround" data-a="'+g+'"><div class="inner_poll">\ud22c\ud45c\ud558\uae30</div></div>',c+="</div>";else{M("#pollType").addClass("poll_content_list");for(g=0;g<h.list.length;g++)c+='<div class="plist" data-b="'+g+'">',c+='\t<div class="inner_item">',c+='\t\t<span class="txt_g">'+
h.list[g].title+"</span>",c+='\t\t<span class="check_item"><span class="ico_ent ico_check"></span></span>',c+="\t</div>",c+="</div>";c+='<div class="btn_poll pround" data-submit-b=""><div class="inner_poll">\ud22c\ud45c\ud558\uae30</div></div>'}M("#pcontent").html(c);M("[data-poll]").data("poll",h.idx)}if(0<M("[data-rank-list]").selector.length){c="";for(g=0;g<rankList.length;g++)c+='<li data-rank-idx="'+rankList[g].idx+'" ',5>g&&(c+="data-new "),"true"===rankList[g].hot&&(c+="data-hot "),c+="data-"+
rankList[g].category,c+=">",f===rankList[g].idx&&(c+='<span class="ico sel"></span>'),c+='<a href="'+rankList[g].url+'">'+rankList[g].title+"</a> ",5>g&&(c+='<span class="ico new"></span>'),"true"===rankList[g].hot&&(c+='<span class="ico hot"></span>'),c+="</li>";M("[data-rank-list]").html(c)}var l=M.storage("io.github.romeoh.poll")||"{}",l=M.json(l);M("[data-a]").on("click",function(c,f){var g=f.data("a");a();e(g)});M("[data-b]").on("click",function(a,c){M("[data-b]").removeClass("on");c.addClass("on");
M("[data-submit-b]").data("submit-b",c.data("b"))});M("[data-submit-b]").on("click",function(c,f){var g=f.data("submit-b");if(!a())return!1;if(""===g)return alert("\ud55c\uac00\uc9c0\ub97c \uc120\ud0dd\ud574\uc8fc\uc138\uc694."),!1;e(g)})};