if(0<M("[data-list]").selector.length){var currentApp=M("[data-list]").data("list"),alist=appList,savedName=M.storage("io.github.romeoh.user.name"),nameStr0=savedName,nameStr1=uniValue(savedName)?savedName+"\uc740":savedName+"\ub294",nameStr2=uniValue(savedName)?savedName+"\uacfc":savedName+"\uc640";savedName&&(alist=appList.replace(/@\ub098\ub294@/g,"@"+nameStr1+"@").replace(/@\ub098\uc5d0\uac8c@/g,"@"+nameStr0+"\uc5d0\uac8c@").replace(/@\ub2f9\uc2e0\uc758@/g,"@"+nameStr0+"\uc758@").replace(/@\ub098\uc758@/g,
"@"+nameStr0+"\uc758@").replace(/@\ub098\uc640@/g,"@"+nameStr2+"@").replace(/@\ub0b4@/g,"@"+nameStr0+"@").replace(/@\ub9d0\uad04\ub7c9\uc774@/g,"@"+nameStr0+"@"));alist=alist.replace(/@/g,"");M("[data-list]").html(alist);M('[data-app="'+currentApp+'"]').prepend("span",{className:"ico sel"})}M("#btnMacao").on("click",function(){window.location.href="http://goo.gl/HMF8gs"});M("#btnMain").on("click",function(){randomUrl()});
function randomUrl(){idx=getRandom(1,totalApp);url=M('[data-app="'+idx+'"]').first().attr("href");window.location.href=url}function getRandom(a,c){return Math.floor(Math.random()*(c-a)+a)}var ua=navigator.userAgent,os=/iphone|ipad|ipod/gi.test(ua)?"ios":/android/gi.test(ua)?"android":/mac/gi.test(ua)?"macOS":/windows/gi.test(ua)?"Windows":"other";
"android"===os&&(idx=getRandom(0,4),eventTxt=['<a href="http://goo.gl/BNYgT">\ud799\ud569\ud14c\ub9c8[\uce74\ud1a1\uc2a4\ud0a8]\uc744 \ubb34\ub8cc\ub85c \ub4dc\ub824\uc694~</a>','<a href="http://goo.gl/WrRJr">\ubd80\uc554\ub3d9\uc0b0\ucc45[\uce74\ud1a1\uc2a4\ud0a8]\uc744 \ubb34\ub8cc\ub85c \ub4dc\ub824\uc694~</a>','<a href="http://goo.gl/otEy6">\ubd88\ud0c0\ub294\uae08\uc694\uc77c[\uce74\ud1a1\uc2a4\ud0a8]\uc744 \ubb34\ub8cc\ub85c \ub4dc\ub824\uc694~</a>','<a href="http://goo.gl/qldVb">\uc218\uc90d\uc740\uc568\ub9ac\uc2a4[\uce74\ud1a1\uc2a4\ud0a8]\uc744 \ubb34\ub8cc\ub85c \ub4dc\ub824\uc694~</a>'],
M("nav").css("display","block").html(eventTxt[idx]));M("#userName").on("change",function(a,c){M.storage("io.github.romeoh.user.name",c.val())}).val(M.storage("io.github.romeoh.user.name")||"");M("#boyBox a").on("click",function(){M("#boyBox a").addClass("checked");M("#girlBox a").removeClass("checked")});M("#girlBox a").on("click",function(){M("#boyBox a").removeClass("checked");M("#girlBox a").addClass("checked")});M("#btnStory").on("click",function(){validation({media:"story"})});
M("#btnTwitter").on("click",function(){validation({media:"twitter"})});M("#btnFacebook").on("click",function(){validation({media:"facebook"})});M("#btnMe2day").on("click",function(){validation({media:"me2day"})});M("#btnKakao").on("click",function(){action({media:"talk"})});
function validation(a){a=a||{};M.storage("io.github.romeoh.user.platform",a.media);if(0<M("#boyBox a").selector.length){if(!M("#boyBox a").hasClass("checked")&&!M("#girlBox a").hasClass("checked"))return alert("\uc131\ubcc4\uc744 \uc120\ud0dd\ud574 \uc8fc\uc138\uc694."),!1;M("#boyBox a").hasClass("checked")?a.sexType="boy":M("#girlBox a").hasClass("checked")&&(a.sexType="girl")}if(0<M("#userName").selector.length){if(""===M("#userName").val())return alert("\uc774\ub984\uc744 \uc785\ub825\ud574 \uc8fc\uc138\uc694."),
!1;a.userName=M("#userName").val()}if(0<M("#selColor").selector.length){if("-1"===M("#selColor").val())return alert("\uc88b\uc544\ud558\ub294 \uc0c9\uc0c1\uc744 \uc120\ud0dd\ud574 \uc8fc\uc138\uc694."),!1;a.color=M("#selColor").val()}if(0<M("#selAlpha").selector.length){if("-1"===M("#selAlpha").val())return alert("\ub5a0\uc624\ub974\ub294 \uc54c\ud30c\ubcb3\uc744 \uc120\ud0dd\ud574 \uc8fc\uc138\uc694."),!1;a.alphabet=M("#selAlpha").val()}if(0<M("#selCoffee").selector.length){if("-1"===M("#selCoffee").val())return alert("\ucee4\ud53c\ub97c \uc8fc\ubb38\ud574 \uc8fc\uc138\uc694."),
!1;a.coffee=M("#selCoffee").val()}if(0<M("#userAge").selector.length){if(""===M("#userAge").val())return alert("\uc0dd\ub144\uc744 \uc785\ub825\ud574 \uc8fc\uc138\uc694."),!1;a.bornYear=M("#userAge").val()}if(0<M("#selYear").selector.length){if("-1"===M("#selYear").val())return alert("\uc0dd\ub144\uc744 \uc120\ud0dd\ud574 \uc8fc\uc138\uc694."),!1;a.bornYear=M("#selYear").val()}if(0<M("#selMonth").selector.length){if("-1"===M("#selMonth").val())return alert("\ud0dc\uc5b4\ub09c \ub2ec\uc744 \uc120\ud0dd\ud574\uc8fc\uc138\uc694."),
!1;a.bornMonth=M("#selMonth").val()}if(0<M("#selDate").selector.length){if("-1"===M("#selDate").val())return alert("\ud0dc\uc5b4\ub09c \ub0a0\uc744 \uc120\ud0dd\ud574\uc8fc\uc138\uc694."),!1;a.bornDate=M("#selDate").val()}if(0<M("#selBlood").selector.length){if("-1"===M("#selBlood").val())return alert("\ud608\uc561\ud615\uc744 \uc120\ud0dd\ud574\uc8fc\uc138\uc694."),!1;a.blood=M("#selBlood").val()}if(0<M("#selSex").selector.length){if("-1"===M("#selSex").val())return alert("\uc131\ubcc4\uc744 \uc120\ud0dd\ud574\uc8fc\uc138\uc694."),
!1;a.sexType=M("#selSex").val()}if(0<M("#selActor").selector.length){if("-1"===M("#selActor").val())return alert("\uc0c1\ub300\uc5f0\uae30\uc790\ub97c \uc120\ud0dd\ud574\uc8fc\uc138\uc694."),!1;a.actor=M("#selActor").val()}if(0<M("#selTall").selector.length){if("-1"===M("#selTall").val())return alert("\ub098\uc758 \ud0a4\ub97c \uc120\ud0dd\ud574\uc8fc\uc138\uc694."),!1;a.tall=M("#selTall").val()}if(0<M("#selIndian").selector.length){if("-1"===M("#selIndian").val())return alert("\uc778\ub514\uc548 \ubd80\uc871\uc744 \uace0\ub974\uc138\uc694."),
!1;a.indian=M("#selIndian").val()}action(a)}function uniValue(a){if(a){a=a.substr(a.length-1).charCodeAt(0)-44032;var c=a%28;parseInt((a-c)/28%21,10);return 0===c?!1:!0}}var bannerData;function showad(){}function closeBanner(){M("#goStore").animate({opacity:"0",time:".3s"},function(a,c){c.css("display","none")});console.log("closeBanner()")}function goStore(){window.location.href=bannerData.link;console.log("goStore()")}
dataBanner=[{url:"bnnr_hippop.html",link:"http://goo.gl/BNYgT"},{url:"bnnr_buam.html",link:"http://goo.gl/WrRJr"},{url:"bnnr_dance.html",link:"http://goo.gl/otEy6"},{url:"bnnr_alice.html",link:"http://goo.gl/qldVb"}];
function sendData(a){var c=a||{},d=c.media||"story",e=c.id||"gaeyou",g=c.ver||"1.0",k=c.app||"\uae68\uc54c\uc720\uba38:",m=c.title||"",h=c.url||"";if("talk"==d)return d=c.msg||m||"",kakao.link("talk").send({msg:d,url:h,appid:e,appver:g,appname:k,type:"link"}),test="\u2665\u2665 [\uce74\ud1a1\uce5c\uad6c \ucd08\ub300] \u2665\u2665\n",test+="appId: "+e+"\n",test+="appVersion: "+g+"\n",test+="appName: "+k+"\n",test+="msg: \n",test+="-----------\n",test+=d+"\n",test+="-----------\n",test+="url: "+h+"\n",
test+="--------------------------------------------\n",console.log(test),!1;if("story"==d){var d=c.post||"",f={title:m,desc:c.desc||"",imageurl:[c.img||""],type:"article"},d=d+"\n\n"+h;kakao.link("story").send({appid:e,appver:g,appname:k,post:d,urlinfo:M.json(f)});return!1}if("twitter"==d)return f="",d=c.post||"",e=h.length+5,g=d.length+e+1,c=140,twit=g>=c?d.substr(0,c-e)+"...\n"+h:d+"\n"+h,twit=twit.replace(/\n\n/g,"\n"),f=f+"https://twitter.com/intent/tweet?text="+encodeURIComponent(twit),top.location.href=
f,!1;if("me2day"==d)return f="",d=c.post||"",k=c.tag||"\uae68\uc54c\uc720\uba38 SNS \ud14c\uc2a4\ud2b8 \uc2ec\ub9ac\ud14c\uc2a4\ud2b8",e=h.length+5,g=d.length+e+1,c=150,me2=g>=c?d.substr(0,c-e)+"...\n"+h:d+"\n"+h,me2=me2.replace(/\n\n/g,"\n"),f+="http://me2day.net/posts/new",f+="?new_post[body]=",f+=encodeURIComponent(me2),f+="&new_post[tags]=",f+=encodeURIComponent(k),top.location.href=f,!1;if("band"==d){var l="",d=c.post||"",e=h.length+3,g=d.length+e+1,c=300;bandPost+="["+k+"]\n";bandPost+=m+": "+
d;b=g>=c?bandPost.substr(0,c-e)+"..."+h:bandPost+" "+h;l=l+"bandapp://create/post?text="+encodeURIComponent(bandPost);l+="#Intent;package=com.nhn.android.band;end;";top.location=f;return!1}if("facebook"==d)return M("body").prepend("script",{src:"https://connect.facebook.net/en_US/all.js",type:"text/javascript",id:"facebookScript"}),M("#facebookScript").on("load",function(c,d){var e=a||{},f=e.mode||"real",g=e.feed||"feed",k=e.method||"post",l=e.photo||e.img||"",n=e.post||"",m=e.scope||"publish_actions, user_photos",
q=e.success||null,r=e.error||null,p={},n=n+"\n\n"+h;"feed"==g?p={message:n,picture:l}:"photo"==g&&(p={message:n,url:l});FB.init({appId:"real"==f?"575459299155222":"199304076906232",channelUrl:"//WWW.YOUR_DOMAIN.COM/channel.html",status:!0,cookie:!0,xfbml:!0});FB.login(function(a){a.authResponse&&FB.api(/me/+g,k,p,function(a){!a||a.error?r&&alert("\uc624\ub958\uac00 \ubc1c\uc0dd\ud588\uc2b5\ub2c8\ub2e4."):q&&alert("\ub4f1\ub85d \ub418\uc5c8\uc2b5\ub2c8\ub2e4.")})},{scope:m});return!1}),!1}
function process(a,c){return"object"===getDataType(a)||"array"===getDataType(a)?Math.floor(Math.random()*a.length):Math.floor(Math.random()*(c-a)+a)}function shuffle(a,c){var d=a.length;c=c||d;for(var e,g;0<d;)g=Math.floor(Math.random()*d),d--,e=a[d],a[d]=a[g],a[g]=e;a.length=c;return a}
function getDataType(a){if("string"===typeof a)return"string";if("number"===typeof a)return"number";if(a.constructor===Object)return"object";if(a.constructor===Array)return"array";if(a.constructor===Function)return"function";if(a.constructor===Boolean)return"boolean"}
if(0<M("#snsBox").selector.length){var appNo=M("[data-list]").data("list"),appName=M('[data-app="'+appNo+'"]').data("page");M("#snsBox").append("div",{className:"fb-like"});M(".fb-like").data("href","http://romeoh.github.io/kakaoStory/html/"+appName+".html").data("width","450").data("layout","button_count").data("showFaces","true").data("send","true")}
(function(a,c,d){var e=a.getElementsByTagName(c)[0];a.getElementById(d)||(a=a.createElement(c),a.id=d,a.src="//connect.facebook.net/ko_KR/all.js#xfbml=1&appId=519730578083610",e.parentNode.insertBefore(a,e))})(document,"script","facebook-jssdk");